version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    privileged: true
    user: root
    environment:
      #设置集群名称为elasticsearch
      - cluster.name=elasticsearch 
      #以单一节点模式启动
      - discovery.type=single-node 
      #设置使用jvm内存大小
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    volumes:
      - /opt/docker_elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /opt/docker_elk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash:7.6.2
    container_name: logstash
    ports:
       - 4560:4560
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      #挂载logstash的配置文件
      - /opt/docker_elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf 
    depends_on:
      - elasticsearch 
    links:
      #可以用es这个域名访问elasticsearch服务
      - elasticsearch:es 
    

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    ports:
        - 5601:5601
    privileged: true
    links:
      #可以用es这个域名访问elasticsearch服务
      - elasticsearch:es 
    depends_on:
      - elasticsearch 
    environment:
      #设置访问elasticsearch的地址
      - elasticsearch.hosts=http://es:9200 
    volumes:
      - "/opt/docker_elk/kibana/config:/usr/share/kibana/config"
   
  oap:
    image: apache/skywalking-ui:8.3.0
    container_name: oap
    ports:
        - 12800:12800
        - 11800:11800
    privileged: true
    links:
      #可以用es这个域名访问elasticsearch服务
      - elasticsearch:es 
    depends_on:
      - elasticsearch 
    environment:
      #设置访问elasticsearch的地址
      - elasticsearch.hosts=http://es:9200 
      - TZ=Asia/Shanghai
      - SW_STORAGE_ES_CLUSTER_NODES=es:9200

  skywalking-ui:
    image: apache/skywalking-ui:8.3.0
    container_name: skywalking-ui
    ports:
        - 8088:8080
    privileged: true
    links:
      #可以用es这个域名访问elasticsearch服务
      - oap:oap 
    depends_on:
      - elasticsearch 
    environment:
      #设置访问elasticsearch的地址
      - SW_OAP_ADDRESS=oap:12800
      - TZ=Asia/Shanghai