version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:2.401.1-lts
    container_name: jenkins
    ports:
      - 8000:8000
      - 50000:50000
    volumes:
      - ./data/:/var/jenkins_home/
